# Пример конфигурационного файла
# Скопируйте этот файл в config.yml и настройте параметры

# Настройки Telegram бота
bot:
  # Токен бота, полученный от @BotFather
  token: "7325259824:AAEAcOL8TbP5lVeO4XRL0cwlKWxIhvuro80"
  
  # Список администраторов бота (Telegram ID)
  admins: []

# Настройки базы данных
database:
  # URL подключения к SQLite базе данных
  url: "sqlite+aiosqlite:///data/whoischeker.db"

# Настройки мониторинга
monitoring:
  # Минимальный интервал проверки (в секундах)
  min_check_interval: 3600  # 1 час
  
  # Максимальный интервал проверки (в секундах)
  max_check_interval: 86400  # 24 часа
  
  # Максимальное количество доменов на пользователя
  max_domains_per_user: 10
  
  # Таймаут для WHOIS запросов (в секундах)
  whois_timeout: 30
  
  # Таймаут для DNS запросов (в секундах)
  dns_timeout: 10

# Настройки логирования
logging:
  # Уровень логирования (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  
  # Путь к файлу логов
  file: "logs/whoischeker.log"
  
  # Максимальный размер файла лога (в байтах)
  max_size: 10485760  # 10 MB
  
  # Количество файлов ротации
  backup_count: 5
  
  # Формат сообщений лога
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 